###

GET http://localhost:9000/members HTTP/1.1

###
GET http://localhost:9000/members/6223980104703445682dc978 HTTP/1.1

###

GET http://localhost:9000/members/Jin HTTP/1.1

###

POST  http://localhost:9000/members HTTP/1.1
Content-Type: application/json

{
    "name": "Kim SeokJin",
    "age": 29,
    "label": "BIGHIT ENT",
    "description": "Singer/Musician",
    "surname": "Jin",
    "random": "Has an Art and Acting degree"
}

###

DELETE  http://localhost:9000/members/6223980104703445682dc978 HTTP/1.1

###

PUT  http://localhost:9000/members/6223980104703445682dc978 HTTP/1.1
Content-Type: application/json

{
    "name": "Min YoonGi",
    "age": 28,
    "label": "BIGHIT ENT.",
    "description": "Raper/Singer/Musician",
    "surname": "SUGA",
    "random": "He plays piano and guitar"
}